const constant = {
    orderTime:[
        {name:"近3天",value:"1"},
        {name:"近7天",value:"2"},
        {name:"近30天",value:"3"},
    ],
    receiveStatus:[
        {name:"认领中",value:"0"},
        {name:"已驳回",value:"1"},
        {name:"待生产",value:"2"},
        {name:"生产中",value:"3"},
        {name:"生产完成",value:"4"},
        {name:"已发货",value:"5"},
        {name:"退单中",value:"6"},
        {name:"已退单",value:"7"},
        {name:"请求返厂",value:"8"},
        {name:"返厂中",value:"9"},
    ],
    source:[
        {name:"淘宝",value:"1"},
        {name:"京东",value:"2"},
        {name:"PDD",value:"3"},
        {name:"线下",value:"4"},
    ],
    deliveryType:[
        {name:"邮寄",value:"1"},
        {name:"同城配送",value:"2"},
        {name:"自提",value:"3"},
    ],
    putongColor:[
        {
            value:1,
            name:'color1',
            color:'#C23247'
        },
        {
            value:2,
            name:'color2',
            color:'#B9DB8F'
        },
        {
            value:3,
            name:'color3',
            color:'#A2DA87'
        },
        {
            value:4,
            name:'color4',
            color:'#89C890'
        },
        {
            value:5,
            name:'color5',
            color:'#7ED5E3'
        },
        {
            value:6,
            name:'color6',
            color:'#8BD9C3'
        },
        {
            value:7,
            name:'color7',
            color:'#5FC6C3'
        },
        {
            value:8,
            name:'color8',
            color:'#CBAE82'
        },
        {
            value:9,
            name:'color9',
            color:'#604A33'
        },
        {
            value:10,
            name:'color10',
            color:'#DFE0E8'
        }
    ],
    aotuColor:[
        {
            value:1,
            name:'color1',
            color:'#C23247'
        },
        {
            value:2,
            name:'color2',
            color:'#F08C4E'
        },
        {
            value:3,
            name:'color3',
            color:'#F0F9F9'
        },
        {
            value:4,
            name:'color4',
            color:'#F8E892'
        },
        {
            value:5,
            name:'color5',
            color:'#FFC25E'
        },
        {
            value:6,
            name:'color6',
            color:'#FFD2B0'
        },
        {
            value:7,
            name:'color7',
            color:'#C1DF96'
        },
        {
            value:8,
            name:'color8',
            color:'#378A53'
        },
        {
            value:9,
            name:'color9',
            color:'#92DAD0'
        },
        {
            value:10,
            name:'color10',
            color:'#169FB6'
        },
        {
            value:11,
            name:'color11',
            color:'#23527B'
        },
    ],
    cailiaoColor:[
        {
            value:1,
            name:'color1',
            color:'#C23247'
        },
        {
            value:2,
            name:'color2',
            color:'#94C7ED'
        },
        {
            value:3,
            name:'color3',
            color:'#ECA8CD'
        },
        {
            value:4,
            name:'color4',
            color:'#D4DEC6'
        },
        {
            value:5,
            name:'color5',
            color:'#E4DAB3'
        },
    ]
};
export default constant