const constant = {
    orderTime:[
        {name:"近3天",value:"1"},
        {name:"近7天",value:"2"},
        {name:"近30天",value:"3"},
    ],
    receiveStatus:[
        {name:"认领中",value:"0"},
        {name:"已驳回",value:"1"},
        {name:"待生产",value:"2"},
        {name:"生产中",value:"3"},
        {name:"生产完成",value:"4"},
        {name:"已发货",value:"5"},
        {name:"退单中",value:"6"},
        {name:"已退单",value:"7"},
        {name:"请求返厂",value:"8"},
        {name:"返厂中",value:"9"},
    ],
    source:[
        {name:"淘宝",value:"1"},
        {name:"京东",value:"2"},
        {name:"PDD",value:"3"},
        {name:"线下",value:"4"},
    ],
    deliveryType:[
        {name:"邮寄",value:"1"},
        {name:"同城配送",value:"2"},
        {name:"自提",value:"3"},
    ],
    putongColor:[
        {
            value:1,
            name:'color1',
            color:'#C23247'
        },
        {
            value:2,
            name:'color2',
            color:'#B9DB8F'
        },
        {
            value:3,
            name:'color3',
            color:'#A2DA87'
        },
        {
            value:4,
            name:'color4',
            color:'#89C890'
        },
        {
            value:5,
            name:'color5',
            color:'#7ED5E3'
        },
        {
            value:6,
            name:'color6',
            color:'#8BD9C3'
        },
        {
            value:7,
            name:'color7',
            color:'#5FC6C3'
        },
        {
            value:8,
            name:'color8',
            color:'#CBAE82'
        },
        {
            value:9,
            name:'color9',
            color:'#604A33'
        },
        {
            value:10,
            name:'color10',
            color:'#DFE0E8'
        }
    ],
    aotuColor:[
        {
            value:1,
            name:'color1',
            color:'#C23247'
        },
        {
            value:2,
            name:'color2',
            color:'#F08C4E'
        },
        {
            value:3,
            name:'color3',
            color:'#F0F9F9'
        },
        {
            value:4,
            name:'color4',
            color:'#F8E892'
        },
        {
            value:5,
            name:'color5',
            color:'#FFC25E'
        },
        {
            value:6,
            name:'color6',
            color:'#FFD2B0'
        },
        {
            value:7,
            name:'color7',
            color:'#C1DF96'
        },
        {
            value:8,
            name:'color8',
            color:'#378A53'
        },
        {
            value:9,
            name:'color9',
            color:'#92DAD0'
        },
        {
            value:10,
            name:'color10',
            color:'#169FB6'
        },
        {
            value:11,
            name:'color11',
            color:'#23527B'
        },
    ],
    cailiaoColor:[
        {
            value:1,
            name:'color1',
            color:'#C23247'
        },
        {
            value:2,
            name:'color2',
            color:'#94C7ED'
        },
        {
            value:3,
            name:'color3',
            color:'#ECA8CD'
        },
        {
            value:4,
            name:'color4',
            color:'#D4DEC6'
        },
        {
            value:5,
            name:'color5',
            color:'#E4DAB3'
        },
    ],

    // 户外写真
    gongyiList1:{
        index:1,
        list:[
            {
                name:"覆亮膜",
                tip:'',
            },
            {
                name:"覆哑膜",
                tip:'',
            },
            {
                name:"四角打扣",
                tip:'',
            },
            {
                name:"裁切",
                tip:'(直角裁切)',
            },
            {
                name:"不裁切",
                tip:'',
            },
            {
                name:"模切",
                tip:'(横切异型)',
            }
        ]
    },
    gongyiList2:{
        index:2,
        list:[
        {
            name:"覆PVC冷裱亮膜",
            tip:'',
          },
          {
            name:"覆PVC冷裱哑膜",
            tip:'',
          },
          {
            name:"覆磨砂地裱膜",
            tip:'',
          },
          {
            name:'四角打扣',
            tip:'',
          },
          {
            name:'覆斜纹地裱膜',
            tip:'',
          },
          {
            name:"裁切",
            tip:'(直角裁切)',
          },
          {
            name:"不裁切",
            tip:'',
          },
          {
            name:"模切",
            tip:'(横切异型)',
          }
    ]
    },
    gongyiList3:{
        index:3,
        list:[
            {
                name:"覆PVC冷裱亮膜",
                tip:'',
            },
            {
                name:"覆PVC冷裱哑膜",
                tip:'',
            },
            {
                name:'四角打扣',
                tip:'',
            },
            {
                name:"不裁切",
                tip:'',
            },
            {
                name:"裁切",
                tip:'(直角裁切)',
            },
            {
                name:"模切",
                tip:'(横切异型)',
            }
        ]
    },
    gongyiList4:{
        index:4,
            list:[
            {
                name:"不裁切",
                tip:'',
            },
            {
                name:"裁切",
                tip:'(直角裁切)',
            },
            {
                name:"模切",
                tip:'(横切异型)',
            }
        ],
    },
    gongyiList5:{
        index:5,
        list:[
            {
                name:'四角打扣',
                tip:'',
            },
            {
                name:"不裁切",
                tip:'',
            },
            {
                name:"裁切",
                tip:'(直角裁切)',
            },
            {
                name:"模切",
                tip:'(横切异型)',
            }
        ],
    },
    gongyiList6:{
        index:6,
        list:[
            {
                name:"覆亮膜",
                tip:'',
            },
            {
                name:"覆哑膜",
                tip:'',
            },
            {
                name:"覆PVC冷裱亮膜",
                tip:'',
            },
            {
                name:"覆PVC冷裱哑膜",
                tip:'',
            },
            {
                name:"四角打扣",
                tip:'',
            },
            {
                name:"裁切",
                tip:'(直角裁切)',
            },
            {
                name:"模切",
                tip:'(横切异型)',
            },
            {
                name:"不裁切",
                tip:'',
            },
        ],
    },
    gongyiList7:{
        index:7,
        list:[
            {
                name:"裁切",
                tip:'(直角裁切)',
            },
        ],
    },
    cailiaoList:[
        {
          name:'户外背胶',
          val:1,
        },
        {
          name:'户外相纸',
          val:1,
        },
        {
          name:'户外正喷灯片',
          val:1,
        },
        {
          name:'户外海报（不带胶）',
          val:1,
        },
        {
          name:'反光膜',
          val:1,
        },
        {
          name:'户外PVC硬片',
          val:1,
        },
        {
          name:'白胶车贴',
          val:2,
        },
        {
          name:'黑胶车贴',
          val:2,
        },
        {
          name:'可移黑胶车贴',
          val:2,
        },
        {
          name:'透明车贴',
          val:3,
        },
        {
          name:'户外单透贴',
          val:4,
        },
        {
          name:'晶彩格',
          val:4,
        },
        {
          name:'户外写真布',
          val:5,
        },
        {
          name:'户外油画布',
          val:5,
        },
        {
          name:'户外银背',
          val:6,
        },
        {
          name:'户外灰背',
          val:6,
        },
        {
          name:'直喷磨砂膜【不喷白色不镂空】',
          val:7,
        }
      ],

    // 条幅
    restaurants1: [
        {
          value:0.5,
          name:'0.5米'
        },
        {
          value:0.6,
          name:' 0.6米'
        },
        {
          value:0.7,
          name:' 0.7米'
        },
        {
          value:0.8,
          name:'0.8米'
        },
        {
          value:0.9,
          name:' 0.9米'
        },
        {
          value:1.0,
          name:' 1.0米'
        },
         {
          value:1.1,
          name:'1.1米'
        },
        {
          value:1.2,
          name:' 1.2米'
        },
        {
          value:1.3,
          name:' 1.3米'
        },
        {
          value:1.4,
          name:' 1.4米'
        },
        {
          value:1.5,
          name:' 1.5米'
        },
        {
          value:1.6,
          name:' 1.6米'
        }
      ],
    restaurants2: [
        {
            value:0.5,
            name:'0.5米 (实际0.45米)'
        },
        {
            value:0.7,
            name:' 0.7米 (实际0.65米)'
        },
        {
            value:0.9,
            name:' 0.9米 (实际0.85米)'
        }
    ],


    // 户内写真
    huneicailiaoList:[
        {
            name:'户内背胶',
            val:1,
        },
        {
            name:'户内高光相纸',
            val:1,
        },
        {
            name:'户内海报（不带胶）',
            val:1,
        },
        {
            name:'户内背喷灯片',
            val:1,
        },
        {
            name:'户内PVC硬片',
            val:1,
        },
        {
            name:'户内银背',
            val:1,
        },
        {
            name:'户内油画布',
            val:2,
        },
        {
            name:'户内写真布',
            val:2,
        },
    ],

    huneigongyiList1:{
        index:1,
        list:[
            {
                name:"覆亮膜",
                tip:'',
            },
            {
                name:"覆哑膜",
                tip:'',
            },
            {
                name:"四角打扣",
                tip:'',
            },
            {
                name:"裁切",
                tip:'(直角裁切)',
            },
            {
                name:"不裁切",
                tip:'',
            },
            {
                name:"模切",
                tip:'(横切异型)',
            }
        ]
    },

    huneigongyiList2:{
        index:2,
        list:[
            {
                name:"四角打扣",
                tip:'',
            },
            {
                name:"裁切",
                tip:'(直角裁切)',
            },
            {
                name:"不裁切",
                tip:'',
            },
            {
                name:"模切",
                tip:'(横切异型)',
            }
        ]
    },

    // 户外精喷
    jingpenCailiaoList:[
        {
            name:'中厚布',
            val:1,
        },
        {
            name:'加厚布',
            val:1,
        },
        {
            name:'黑白布',
            val:1,
        },
        {
            name:'大网格布（带孔）',
            val:1,
        },
        {
            name:'刀刮布外光',
            val:1,
        },
        {
            name:'刀刮布内光',
            val:1,
        },
        {
            name:'PET灯片',
            val:1,
        },
    ],

    jingpenGongyiList1:{
        index:1,
        list:[
            {
                name:"正常留白",
                tip:'',
            },
            {
                name:"剪净边",
                tip:'',
            },
            {
                name:"净边打扣",
                tip:'',
            },
            {
                name:"留白打扣",
                tip:'',
            },
            {
                name:"净边穿绳打扣",
                tip:'',
            },
            {
                name:"留白穿绳打扣",
                tip:'',
            },
            {
                name:"模切",
                tip:'(横切异型)',
            }
        ]
    },

    // 喷绘
    penyhuiCailiaoList:[
        {
            name:'中厚布',
            val:1,
        },
        {
            name:'加厚布',
            val:1,
        },
        {
            name:'黑白布',
            val:1,
        },
        {
            name:'大网格布（带孔）',
            val:1,
        },
        {
            name:'刀刮布外光',
            val:1,
        },
        {
            name:'刀刮布内光',
            val:1,
        },
        {
            name:'反光喷绘布',
            val:1,
        },
    ],


};
export default constant
